# Generated by Django 5.0 on 2026-01-24 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indoApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banner_type', models.CharField(choices=[('HERO', 'Hero Carousel'), ('EXCLUSIVE', 'Exclusive Banner'), ('TOP_BRANDS', 'Top Brands Banner'), ('OFFERS', 'Offers Banner')], db_index=True, max_length=20)),
                ('image', models.ImageField(upload_to='home_banners/')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('banner_type', 'sort_order', '-created_at'),
                'indexes': [models.Index(fields=['banner_type', 'is_active'], name='indoApp_hom_banner__7670cf_idx')],
            },
        ),
    ]
