# Generated by Django 5.0 on 2026-01-21 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indoApp', '0002_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='min_order_quantity',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
