# Generated by Django 5.0 on 2026-01-24 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indoApp', '0002_homebanner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homebanner',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
