# Generated by Django 5.0 on 2026-01-21 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indoApp', '0003_product_min_order_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_exclusive',
            field=models.BooleanField(default=False),
        ),
    ]
