# Generated by Django 5.0 on 2026-01-26 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indoApp', '0003_alter_homebanner_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.CreateModel(
            name='LatestLaunches',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='latest_launches/')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['is_active'], name='indoApp_lat_is_acti_765bd4_idx')],
            },
        ),
    ]
