# Generated by Django 5.0 on 2026-01-22 05:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indoApp', '0004_product_is_exclusive'),
    ]

    operations = [
        migrations.CreateModel(
            name='BrandBrochure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brochure_file', models.FileField(upload_to='brand_brochures/')),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='brochures', to='indoApp.brand')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='brand_brochures', to='indoApp.category')),
            ],
            options={
                'indexes': [models.Index(fields=['brand'], name='indoApp_bra_brand_i_18f6ab_idx'), models.Index(fields=['category'], name='indoApp_bra_categor_fa9eaf_idx')],
                'unique_together': {('brand', 'category')},
            },
        ),
    ]
