# Generated by Django 5.0 on 2026-01-27 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indoApp', '0004_alter_product_price_latestlaunches'),
    ]

    operations = [
        migrations.CreateModel(
            name='OffersAndSchemes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='offers_and_schemes/')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('valid_upto', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['is_active'], name='indoApp_off_is_acti_5c5458_idx')],
            },
        ),
    ]
