# Generated by Django 5.0 on 2026-01-22 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indoApp', '0005_brandbrochure'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
    ]
