# Generated by Django 5.0 on 2026-01-27 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indoApp', '0005_offersandschemes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offersandschemes',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
