# Generated by Django 5.0 on 2026-01-22 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indoApp', '0006_product_is_featured'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='rating',
            field=models.IntegerField(default=5),
        ),
    ]
