# Generated by Django 5.0 on 2026-01-27 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indoApp', '0006_alter_offersandschemes_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offersandschemes',
            name='valid_upto',
            field=models.DateField(blank=True, null=True),
        ),
    ]
