# Generated by Django 5.0 on 2026-01-29 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indoApp', '0007_alter_offersandschemes_valid_upto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homebanner',
            name='banner_type',
            field=models.CharField(choices=[('HERO', 'Hero Carousel'), ('EXCLUSIVE', 'Exclusive Banner'), ('TOP_BRANDS', 'Top Brands Banner'), ('OFFERS', 'Offers Banner'), ('HERO_MOBILE', 'Hero Carousel Mobile'), ('EXCLUSIVE_MOBILE', 'Exclusive Banner Mobile'), ('TOP_BRANDS_MOBILE', 'Top Brands Banner Mobile'), ('OFFERS_MOBILE', 'Offers Banner Mobile')], db_index=True, max_length=20),
        ),
    ]
