# Generated by Django 5.0 on 2026-01-29 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indoApp', '0008_alter_homebanner_banner_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='min_order_quantity',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
